/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package residencymanagement;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author matal
 */
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
        
        conn = dbConnection.conn();
        
        adlogin_panel.setVisible(false);
        selogin_panel.setVisible(false);
        
        selogin_panel.setVisible(false);
        adlogin_panel.setVisible(true);
        
        btnAdminLogin.setBackground(new Color(86,70,120));
        btnSecurityLogin.setBackground(new Color(64,43,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSecurityLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adlogin_panel = new javax.swing.JPanel();
        btn_admin_proceed = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        tf_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selogin_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_username1 = new javax.swing.JTextField();
        btn_login_proceed = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residency Management");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        btnAdminLogin.setBackground(new java.awt.Color(64, 43, 100));
        btnAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminLoginMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN LOGIN");

        javax.swing.GroupLayout btnAdminLoginLayout = new javax.swing.GroupLayout(btnAdminLogin);
        btnAdminLogin.setLayout(btnAdminLoginLayout);
        btnAdminLoginLayout.setHorizontalGroup(
            btnAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdminLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnAdminLoginLayout.setVerticalGroup(
            btnAdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdminLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSecurityLogin.setBackground(new java.awt.Color(64, 43, 100));
        btnSecurityLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecurityLoginMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SECURITY LOGIN");

        javax.swing.GroupLayout btnSecurityLoginLayout = new javax.swing.GroupLayout(btnSecurityLogin);
        btnSecurityLogin.setLayout(btnSecurityLoginLayout);
        btnSecurityLoginLayout.setHorizontalGroup(
            btnSecurityLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSecurityLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSecurityLoginLayout.setVerticalGroup(
            btnSecurityLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSecurityLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        adlogin_panel.setBackground(new java.awt.Color(237, 237, 237));
        adlogin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_admin_proceed.setBackground(new java.awt.Color(46, 52, 64));
        btn_admin_proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_admin_proceedMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Login");

        javax.swing.GroupLayout btn_admin_proceedLayout = new javax.swing.GroupLayout(btn_admin_proceed);
        btn_admin_proceed.setLayout(btn_admin_proceedLayout);
        btn_admin_proceedLayout.setHorizontalGroup(
            btn_admin_proceedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_admin_proceedLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_admin_proceedLayout.setVerticalGroup(
            btn_admin_proceedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        adlogin_panel.add(btn_admin_proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 90, 40));

        tf_password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        adlogin_panel.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 160, 40));

        tf_username.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        adlogin_panel.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 160, 40));

        jLabel10.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ADMIN");
        adlogin_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 50));

        jLabel5.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username:");
        adlogin_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 50));

        jLabel4.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password:");
        adlogin_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 50));

        selogin_panel.setBackground(new java.awt.Color(237, 237, 237));
        selogin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");
        selogin_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 50));

        jLabel8.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Username:");
        selogin_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 50));

        tf_username1.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        selogin_panel.add(tf_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 160, 40));

        btn_login_proceed.setBackground(new java.awt.Color(46, 52, 64));
        btn_login_proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_login_proceedMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Login");

        javax.swing.GroupLayout btn_login_proceedLayout = new javax.swing.GroupLayout(btn_login_proceed);
        btn_login_proceed.setLayout(btn_login_proceedLayout);
        btn_login_proceedLayout.setHorizontalGroup(
            btn_login_proceedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_login_proceedLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_login_proceedLayout.setVerticalGroup(
            btn_login_proceedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        selogin_panel.add(btn_login_proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 90, 40));

        jLabel11.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("SECURITY");
        selogin_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, 50));

        tf_password1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        selogin_panel.add(tf_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 160, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSecurityLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adlogin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selogin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSecurityLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(selogin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adlogin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLoginMouseClicked
        selogin_panel.setVisible(false);
        adlogin_panel.setVisible(true);
        
        btnAdminLogin.setBackground(new Color(86,70,120));
        btnSecurityLogin.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btnAdminLoginMouseClicked

    private void btn_admin_proceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admin_proceedMouseClicked
        String username = tf_username.getText();
        String password = tf_password.getText();
        
        try{
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM admin WHERE ad_name="+"'"+username+"'"+" AND ad_pwd="+"'"+password+"'";
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next()){
                dispose();
                Admin_Panel adPanel = new Admin_Panel();
                adPanel.setVisible(true);
                adPanel.setAdminId(rs.getString("ad_name"));
                adPanel.setSocName(rs.getString("soc_name"));
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                return;
            }
            
        }
        catch(Exception e){
            System.out.print(e.getMessage().toString());
        }
    }//GEN-LAST:event_btn_admin_proceedMouseClicked

    private void btnSecurityLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecurityLoginMouseClicked
        adlogin_panel.setVisible(false);
        selogin_panel.setVisible(true);
        
        btnSecurityLogin.setBackground(new Color(86,70,120));
        btnAdminLogin.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btnSecurityLoginMouseClicked

    private void btn_login_proceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_login_proceedMouseClicked

        String username = tf_username1.getText();
        String password = tf_password1.getText();
        
        try{
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM security WHERE sec_name="+"'"+username+"'"+" AND sec_pwd="+"'"+password+"'";
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next()){
                dispose();
                SecurityDashboard secDash = new SecurityDashboard();
                secDash.setSecurityId(rs.getString("sec_name"));
                secDash.setSocName(rs.getString("soc_name"));
                secDash.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
                return;
            }
            
        }
        catch(Exception e){
            System.out.print(e.getMessage().toString());
        }
        
    }//GEN-LAST:event_btn_login_proceedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adlogin_panel;
    private javax.swing.JPanel btnAdminLogin;
    private javax.swing.JPanel btnSecurityLogin;
    private javax.swing.JPanel btn_admin_proceed;
    private javax.swing.JPanel btn_login_proceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel selogin_panel;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JPasswordField tf_password1;
    private javax.swing.JTextField tf_username;
    private javax.swing.JTextField tf_username1;
    // End of variables declaration//GEN-END:variables
}
