/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package residencymanagement;

import java.sql.*;
import java.util.Calendar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.twilio.Twilio; 

import com.twilio.rest.api.v2010.account.Message; 

import java.awt.Font;

 

import java.text.SimpleDateFormat;

import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author patel
 */
public class SecurityDashboard extends javax.swing.JFrame {
    
    Connection conn = null;
    String bNo, hNo, id, indBlockNo, indHouseNo;
    
    private Document document;
    private PdfWriter writer;
    
    private String securityId = null;
    private String socName = null;
    
    boolean dtset=false;
    
    /**
     * Creates new form SecurityDashboard
     */
    public SecurityDashboard() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("home.png")));
        
        switchPanels(newEntryPanel);
        
        conn = dbConnection.conn();
        logsTable.getTableHeader().setFont(new Font("Product Sans", Font.BOLD, 13));
        indLogsTable.getTableHeader().setFont(new Font("Product Sans", Font.BOLD, 13));
        
        inactiveButton();
        activeButton(btnNewEntry, jPanel10);
        jPanel2.setVisible(false);
        btnNext.setVisible(false);
    }
    
    public void setSecurityId(String id) {
        securityId = id;
        txtSecurity.setText("Welcome "+securityId+"!");
    }
    
    public void setSocName(String soc) {
        socName = soc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        navPane = new javax.swing.JPanel();
        btnNewEntry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnLogs = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btnIndividualLogs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        txtSecurity = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        newEntryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbBlockNo = new javax.swing.JComboBox<>();
        txtHouseNo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblResiName = new javax.swing.JLabel();
        lblResiAddress = new javax.swing.JLabel();
        lblResiContact = new javax.swing.JLabel();
        btnNext = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        visitorEntryPanel = new javax.swing.JPanel();
        txtVisitorName = new javax.swing.JTextField();
        txtVisitorContact = new javax.swing.JTextField();
        txtVisitorVehNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        logsPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logsTable = new javax.swing.JTable();
        logsDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        toTimeCB = new javax.swing.JComboBox<>();
        fromTimeCB = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnLogsSearch = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnDownloadPdf = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        individualLogsPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        indLogsTable = new javax.swing.JTable();
        btnIndLogsSearch = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnIndDownloadPdf = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbIndBlockNo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtIndHouseNo = new javax.swing.JTextField();
        btnSendMail = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residency Management");
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navPane.setBackground(new java.awt.Color(55, 38, 92));
        navPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewEntry.setBackground(new java.awt.Color(86, 70, 120));
        btnNewEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNewEntryMousePressed(evt);
            }
        });
        btnNewEntry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Entry");
        btnNewEntry.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 100, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnNewEntry.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        navPane.add(btnNewEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 50));

        btnLogs.setBackground(new java.awt.Color(64, 43, 100));
        btnLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogsMousePressed(evt);
            }
        });
        btnLogs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logs");
        btnLogs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 67, 50));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnLogs.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        navPane.add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 50));

        btnLogOut.setBackground(new java.awt.Color(64, 43, 100));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        btnLogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Log Out");
        btnLogOut.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 67, 50));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnLogOut.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        navPane.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 50));

        btnIndividualLogs.setBackground(new java.awt.Color(64, 43, 100));
        btnIndividualLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIndividualLogsMousePressed(evt);
            }
        });
        btnIndividualLogs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Individual Logs");
        btnIndividualLogs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 113, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnIndividualLogs.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        navPane.add(btnIndividualLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 50));

        jLabel35.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("SECURITY");
        navPane.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtSecurity.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        txtSecurity.setForeground(new java.awt.Color(255, 255, 255));
        navPane.add(txtSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        jPanel14.setPreferredSize(new java.awt.Dimension(150, 1));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        navPane.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        background.add(navPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 530));

        newEntryPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("House No. :");

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Block No. :");

        jPanel1.setBackground(new java.awt.Color(46, 52, 64));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Submit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        cbBlockNo.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        cbBlockNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" }));

        txtHouseNo.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        txtHouseNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));

        jLabel8.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");

        jLabel9.setFont(new java.awt.Font("Product Sans", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resident Details:");

        jLabel10.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact No.:");

        jLabel11.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");

        lblResiName.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        lblResiName.setForeground(new java.awt.Color(255, 255, 255));

        lblResiAddress.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        lblResiAddress.setForeground(new java.awt.Color(255, 255, 255));

        lblResiContact.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        lblResiContact.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblResiName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResiAddress)
                            .addComponent(lblResiContact))))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lblResiName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lblResiAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResiContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        btnNext.setBackground(new java.awt.Color(46, 52, 64));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Next ->");

        javax.swing.GroupLayout btnNextLayout = new javax.swing.GroupLayout(btnNext);
        btnNext.setLayout(btnNextLayout);
        btnNextLayout.setHorizontalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNextLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btnNextLayout.setVerticalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("New Visitor Entry");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout newEntryPanelLayout = new javax.swing.GroupLayout(newEntryPanel);
        newEntryPanel.setLayout(newEntryPanelLayout);
        newEntryPanelLayout.setHorizontalGroup(
            newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newEntryPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newEntryPanelLayout.createSequentialGroup()
                        .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newEntryPanelLayout.setVerticalGroup(
            newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEntryPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newEntryPanelLayout.createSequentialGroup()
                        .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(newEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        visitorEntryPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtVisitorName.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        txtVisitorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtVisitorContact.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        txtVisitorContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtVisitorContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVisitorContactFocusLost(evt);
            }
        });

        txtVisitorVehNo.setFont(new java.awt.Font("Product Sans", 0, 15)); // NOI18N
        txtVisitorVehNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contact No. :");

        jLabel14.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Vehicle No. :");

        jLabel15.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Name :");

        jPanel3.setBackground(new java.awt.Color(46, 52, 64));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Submit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(85, 65, 118));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("New Visitor Entry");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout visitorEntryPanelLayout = new javax.swing.GroupLayout(visitorEntryPanel);
        visitorEntryPanel.setLayout(visitorEntryPanelLayout);
        visitorEntryPanelLayout.setHorizontalGroup(
            visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(visitorEntryPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(visitorEntryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtVisitorContact))
                    .addGroup(visitorEntryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVisitorName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(visitorEntryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVisitorVehNo))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        visitorEntryPanelLayout.setVerticalGroup(
            visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitorEntryPanelLayout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVisitorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtVisitorName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(visitorEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtVisitorVehNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        logsPanel.setBackground(new java.awt.Color(255, 255, 255));
        logsPanel.setForeground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Entry Logs");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        logsTable.setAutoCreateRowSorter(true);
        logsTable.setBackground(new java.awt.Color(255, 255, 255));
        logsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Block No.", "House No.", "Name", "Vehicle No.", "Contact No.", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logsTable.setGridColor(new java.awt.Color(255, 255, 255));
        logsTable.setRowHeight(30);
        jScrollPane1.setViewportView(logsTable);

        logsDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                logsDateChooserFocusLost(evt);
            }
        });
        logsDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                logsDateChooserPropertyChange(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Choose Date:");

        toTimeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "23:59" }));
        toTimeCB.setSelectedIndex(24);

        fromTimeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "23:59" }));

        jLabel19.setText("From:");

        jLabel20.setText("To:");

        btnLogsSearch.setBackground(new java.awt.Color(46, 52, 64));
        btnLogsSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnLogsSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogsSearchMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Search");

        javax.swing.GroupLayout btnLogsSearchLayout = new javax.swing.GroupLayout(btnLogsSearch);
        btnLogsSearch.setLayout(btnLogsSearchLayout);
        btnLogsSearchLayout.setHorizontalGroup(
            btnLogsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogsSearchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLogsSearchLayout.setVerticalGroup(
            btnLogsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        btnDownloadPdf.setBackground(new java.awt.Color(46, 52, 64));
        btnDownloadPdf.setForeground(new java.awt.Color(255, 255, 255));
        btnDownloadPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDownloadPdfMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Download PDF");

        javax.swing.GroupLayout btnDownloadPdfLayout = new javax.swing.GroupLayout(btnDownloadPdf);
        btnDownloadPdf.setLayout(btnDownloadPdfLayout);
        btnDownloadPdfLayout.setHorizontalGroup(
            btnDownloadPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDownloadPdfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btnDownloadPdfLayout.setVerticalGroup(
            btnDownloadPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout logsPanelLayout = new javax.swing.GroupLayout(logsPanel);
        logsPanel.setLayout(logsPanelLayout);
        logsPanelLayout.setHorizontalGroup(
            logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logsPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logsPanelLayout.createSequentialGroup()
                        .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLogsSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logsDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(logsPanelLayout.createSequentialGroup()
                        .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDownloadPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        logsPanelLayout.setVerticalGroup(
            logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logsDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fromTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDownloadPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        individualLogsPanel.setBackground(new java.awt.Color(255, 255, 255));
        individualLogsPanel.setForeground(new java.awt.Color(0, 0, 0));

        jPanel9.setBackground(new java.awt.Color(85, 65, 118));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Individual Entry Logs");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        indLogsTable.setAutoCreateRowSorter(true);
        indLogsTable.setBackground(new java.awt.Color(255, 255, 255));
        indLogsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        indLogsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Block No.", "House No.", "Name", "Vehicle No.", "Contact No.", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        indLogsTable.setGridColor(new java.awt.Color(255, 255, 255));
        indLogsTable.setRowHeight(30);
        jScrollPane2.setViewportView(indLogsTable);

        btnIndLogsSearch.setBackground(new java.awt.Color(46, 52, 64));
        btnIndLogsSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnIndLogsSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIndLogsSearchMousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Search");

        javax.swing.GroupLayout btnIndLogsSearchLayout = new javax.swing.GroupLayout(btnIndLogsSearch);
        btnIndLogsSearch.setLayout(btnIndLogsSearchLayout);
        btnIndLogsSearchLayout.setHorizontalGroup(
            btnIndLogsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIndLogsSearchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel26)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btnIndLogsSearchLayout.setVerticalGroup(
            btnIndLogsSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        btnIndDownloadPdf.setBackground(new java.awt.Color(46, 52, 64));
        btnIndDownloadPdf.setForeground(new java.awt.Color(255, 255, 255));
        btnIndDownloadPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIndDownloadPdfMousePressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Download PDF");

        javax.swing.GroupLayout btnIndDownloadPdfLayout = new javax.swing.GroupLayout(btnIndDownloadPdf);
        btnIndDownloadPdf.setLayout(btnIndDownloadPdfLayout);
        btnIndDownloadPdfLayout.setHorizontalGroup(
            btnIndDownloadPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIndDownloadPdfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel27)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        btnIndDownloadPdfLayout.setVerticalGroup(
            btnIndDownloadPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLabel23.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Block No. :");

        cbIndBlockNo.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        cbIndBlockNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" }));

        jLabel24.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("House No. :");

        txtIndHouseNo.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        txtIndHouseNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnSendMail.setBackground(new java.awt.Color(46, 52, 64));
        btnSendMail.setForeground(new java.awt.Color(255, 255, 255));
        btnSendMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSendMailMousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Send Mail");

        javax.swing.GroupLayout btnSendMailLayout = new javax.swing.GroupLayout(btnSendMail);
        btnSendMail.setLayout(btnSendMailLayout);
        btnSendMailLayout.setHorizontalGroup(
            btnSendMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSendMailLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel28)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        btnSendMailLayout.setVerticalGroup(
            btnSendMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout individualLogsPanelLayout = new javax.swing.GroupLayout(individualLogsPanel);
        individualLogsPanel.setLayout(individualLogsPanelLayout);
        individualLogsPanelLayout.setHorizontalGroup(
            individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, individualLogsPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(individualLogsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbIndBlockNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIndHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, individualLogsPanelLayout.createSequentialGroup()
                        .addGroup(individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIndLogsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(individualLogsPanelLayout.createSequentialGroup()
                                .addComponent(btnIndDownloadPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnSendMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        individualLogsPanelLayout.setVerticalGroup(
            individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(individualLogsPanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIndBlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnIndLogsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(individualLogsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSendMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIndDownloadPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLayeredPane1.setLayer(newEntryPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(visitorEntryPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(logsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(individualLogsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newEntryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(visitorEntryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(logsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(individualLogsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newEntryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(visitorEntryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(logsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(individualLogsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 800, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewEntryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewEntryMousePressed
        // TODO add your handling code here:
        switchPanels(newEntryPanel);
        jPanel2.setVisible(false);
        btnNext.setVisible(false);
        
        lblResiName.setText("");
        lblResiAddress.setText("");
        lblResiContact.setText("");
        
        inactiveButton();
        activeButton(btnNewEntry, jPanel10);
    }//GEN-LAST:event_btnNewEntryMousePressed

    private void btnLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMousePressed
        // TODO add your handling code here:
        switchPanels(logsPanel);
        
        inactiveButton();
        activeButton(btnLogs, jPanel11);
        
        addLogs(logsTable, "select * from visitor");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        dtset = false;
    }//GEN-LAST:event_btnLogsMousePressed

    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:   
        bNo = (String) cbBlockNo.getSelectedItem();
        hNo = txtHouseNo.getText();
        id = null;
        
        if(bNo.equals("")||hNo.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter house no.");
            return;
        }
        
        
        
        try {
            Statement selectStmt = conn.createStatement();
            ResultSet rs = selectStmt.executeQuery("SELECT * FROM resident WHERE res_block='" +bNo+ "' AND res_house_no='" + hNo + "'");
            
            if(!rs.isBeforeFirst()) {
                jPanel2.setVisible(false);
                btnNext.setVisible(false);
                JOptionPane.showMessageDialog(this, "No record found!");
                return;
            }
            
            while(rs.next()) {
                lblResiName.setText(rs.getString(2));
                lblResiAddress.setText(rs.getString(3)+" "+rs.getString(4));
                id = rs.getString(1);
                
                jPanel2.setVisible(true);
                btnNext.setVisible(true);
            }
            
            ResultSet rs2 = selectStmt.executeQuery("SELECT * FROM resident_contact WHERE res_id="+id);
            while(rs2.next()) {
                lblResiContact.setText(lblResiContact.getText()+rs2.getString(2)+", ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMousePressed
        // TODO add your handling code here:
        switchPanels(visitorEntryPanel);
        lblResiName.setText("");
        lblResiAddress.setText("");
        lblResiContact.setText("");
    }//GEN-LAST:event_btnNextMousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        String visName = txtVisitorName.getText();
        String visContact = txtVisitorContact.getText();
        String visVehNo = txtVisitorVehNo.getText();
        
        java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
        Calendar cal = Calendar.getInstance();
        java.sql.Timestamp ourJavaTimestampObject = new java.sql.Timestamp(cal.getTime().getTime());
        
        
        Thread t1=new Thread(){  
            public void run(){ 
                 try {
                    Statement selectStmt = conn.createStatement();
                    String query = "INSERT INTO visitor (vis_name,vis_block,vis_house_no,vehicle_no, vis_contact, vis_entry) VALUES (?,?,?,?,?,?)";
                    PreparedStatement preparedStatement = conn.prepareStatement(query);
                    preparedStatement.setString(1, visName);
                    preparedStatement.setString(2, bNo);
                    preparedStatement.setString(3, hNo);
                    preparedStatement.setString(4, visVehNo);
                    preparedStatement.setString(5, visContact);
                    preparedStatement.setTimestamp(6, ourJavaTimestampObject);

                            //+visName+"','"+bNo+"','"+hNo+"','"+visVehNo+"','"+visContact+"',"+(currentTimestamp);
                    preparedStatement.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Entry successful!");

                    switchPanels(newEntryPanel);

                } catch (SQLException ex) {
                    Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
        };  
        Thread t2=new Thread(){  
            public void run(){  
                String ACCOUNT_SID = "AC62fbadb4842e9175147a831fc8d1611e"; 
                String AUTH_TOKEN = "0c606600416892107946e55c019cf6a5";
                
                Statement selectStmt;
                try {
                    selectStmt = conn.createStatement();
                    ResultSet rs = selectStmt.executeQuery("SELECT * FROM resident_contact WHERE res_id=" + id);
                    
                    while(rs.next()) {
                        Twilio.init(ACCOUNT_SID, AUTH_TOKEN); 
                        Message message = Message.creator( 
                                new com.twilio.type.PhoneNumber("whatsapp:+91"+rs.getString(2)),
                                new com.twilio.type.PhoneNumber("whatsapp:+14155238886"),
                                "\nYou got a new visitor!!!\n\n"+"Name: "+visName+"\nVehicle No.: "+visVehNo+"\nContact No.: "+visContact)
                            .create();

                        System.out.println(message.getSid()); 
                    }

                    

                } catch (SQLException ex) {
                    Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error Sending Message!");
                }
                
                
            }  
        };  


        t1.start();  
        t2.start();
        
    }//GEN-LAST:event_jPanel3MousePressed

    private void txtVisitorContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVisitorContactFocusLost
        // TODO add your handling code here:
        String visContact = txtVisitorContact.getText();
        
        Statement selectStmt;
        try {
            selectStmt = conn.createStatement();
            ResultSet rs = selectStmt.executeQuery("SELECT * FROM visitor WHERE vis_contact='" +visContact+ "'");
            
            while(rs.next()) {
                txtVisitorName.setText(rs.getString(2));
                txtVisitorVehNo.setText(rs.getString(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtVisitorContactFocusLost

    
    
    
    
    private void btnIndLogsSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndLogsSearchMousePressed
        // TODO add your handling code here:
        indBlockNo = cbIndBlockNo.getSelectedItem().toString();
        indHouseNo = txtIndHouseNo.getText();
        
        if(indHouseNo.equals("")) {
            JOptionPane.showMessageDialog(this, "Please select house no.!");
            return;
        }
        
        addLogs(indLogsTable, "select * from visitor where vis_block='"+indBlockNo+"' and vis_house_no='"+indHouseNo+"'");
    }//GEN-LAST:event_btnIndLogsSearchMousePressed

    private void btnIndDownloadPdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndDownloadPdfMousePressed
        // TODO add your handling code here:
        try {
            JFrame parentcomp = new JFrame();
        
            JFileChooser fc = new JFileChooser();
            int retVal = fc.showOpenDialog(parentcomp);
            if(retVal == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fc.getSelectedFile();
                PdfPTable pdfTable = new PdfPTable(indLogsTable.getColumnCount());
                SavePDF.openPdf(fileToSave);
                SavePDF.addData(pdfTable, indLogsTable, "Visitor Log Entries\n", indBlockNo+" "+indHouseNo+"\n\n");
                SavePDF.closePdf();
            }
        } catch (FileNotFoundException e1) {
            e1.printStackTrace();
        } catch (DocumentException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnIndDownloadPdfMousePressed

    private void btnIndividualLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndividualLogsMousePressed
        // TODO add your handling code here:
        switchPanels(individualLogsPanel);
        
        inactiveButton();
        activeButton(btnIndividualLogs, jPanel12);
//        try {
//            ReceiptPDF.createReceipt();
//        } catch (IOException ex) {
//            Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (DocumentException ex) {
//            Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnIndividualLogsMousePressed

    private void btnSendMailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMailMousePressed
        // TODO add your handling code here:
        try {
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());
            System.out.println(timestamp);

            PdfPTable pdfTable = new PdfPTable(indLogsTable.getColumnCount());
            JFrame parentcomp = new JFrame();
            
            File fileToSave = null;
        
                JFileChooser fc = new JFileChooser();
                int retVal = fc.showOpenDialog(parentcomp);
                if(retVal == JFileChooser.APPROVE_OPTION) {
                    fileToSave = fc.getSelectedFile();
                    SavePDF.openPdf(fileToSave);
                    SavePDF.addData(pdfTable, indLogsTable, "Visitor Log Entries\n", indBlockNo+" "+indHouseNo+"\n\n");
                    SavePDF.closePdf();
                }
            
            Statement stmt = conn.createStatement();
            String query = "select res_email from resident where res_block='"+indBlockNo+"' and res_house_no='" +indHouseNo+"'";
            ResultSet rs = stmt.executeQuery(query);
            String receiver = null;
            while(rs.next()) {
                receiver = rs.getString(1);
            }
            File f = new File(fileToSave+".pdf");
            SendMailPDF.sendMail(receiver, f, "Individual Logs", "Visitor Log Entries of your house");
        } catch (FileNotFoundException e1) {
            e1.printStackTrace();
        } catch (DocumentException e1) {
            e1.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(SecurityDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendMailMousePressed

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        Frame f = new Frame();
        UIManager.put("OptionPane.yesButtonText", "Yes");
        UIManager.put("OptionPane.noButtonText", "Cancel");
        
        int a=JOptionPane.showConfirmDialog(f,"Are you sure you want to logout?", "Question", JOptionPane.YES_NO_OPTION );
        
        if(a==JOptionPane.YES_OPTION) {
            id = null;
            indBlockNo = null;
            indHouseNo = null;
            bNo = null;
            hNo = null;
            securityId = null;
            socName = null;
            dispose();

            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnDownloadPdfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownloadPdfMousePressed
        // TODO add your handling code here:
        try {
            if(dtset==false) {
                JOptionPane.showMessageDialog(this, "Please select date!");
            }
            JFrame parentcomp = new JFrame();

            Timestamp ts = new Timestamp(logsDateChooser.getDate().getTime());

            String fromTime = fromTimeCB.getSelectedItem().toString();
            String toTime = toTimeCB.getSelectedItem().toString();

            SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
            sdfDate.setTimeZone(java.util.TimeZone.getTimeZone("IST"));
            String dt = sdfDate.format(ts);

            JFileChooser fc = new JFileChooser();
            int retVal = fc.showOpenDialog(parentcomp);
            if(retVal == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fc.getSelectedFile();
                PdfPTable pdfTable = new PdfPTable(logsTable.getColumnCount());
                SavePDF.openPdf(fileToSave);
                SavePDF.addData(pdfTable, logsTable, "Visitor Logs Entry\n", dt+" ("+fromTime+"-"+toTime+")\n\n");
                SavePDF.closePdf();

                JOptionPane.showMessageDialog(this, "PDF saved!");
            }

        } catch (FileNotFoundException e1) {
            e1.printStackTrace();
        } catch (DocumentException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnDownloadPdfMousePressed

    private void btnLogsSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsSearchMousePressed
        // TODO add your handling code here:

        Timestamp ts = new Timestamp(logsDateChooser.getDate().getTime());
        System.out.println(ts);

        String fromTime = fromTimeCB.getSelectedItem().toString();
        String toTime = toTimeCB.getSelectedItem().toString();

        //        String fromTime = ts.toString();

        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
        sdfDate.setTimeZone(java.util.TimeZone.getTimeZone("IST"));
        String dt = sdfDate.format(ts);

        System.out.println(dt);

        addLogs(logsTable, "select * from visitor where vis_entry between '" + dt + " " + fromTime + ":00' and '" + dt + " " + toTime + ":59'");
        dtset=true;
    }//GEN-LAST:event_btnLogsSearchMousePressed

    private void logsDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_logsDateChooserPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_logsDateChooserPropertyChange

    private void logsDateChooserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logsDateChooserFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_logsDateChooserFocusLost

    /**
     * @param args the command line arguments
     */
    
    public void switchPanels(JPanel panel) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
    
    public void addLogs(javax.swing.JTable table, String q) {
        try {
            Statement stmt = conn.createStatement();
            String query = q;
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            
            SimpleDateFormat sdfDate = new SimpleDateFormat("dd-MM-yyyy");
            sdfDate.setTimeZone(java.util.TimeZone.getTimeZone("IST"));

            SimpleDateFormat sdfTime = new SimpleDateFormat("hh:mm:ss a");
            sdfTime.setTimeZone(java.util.TimeZone.getTimeZone("IST"));
            
            if(!rs.isBeforeFirst()) {
                JOptionPane.showMessageDialog(this, "No record found!");
                return;
            }

            tblModel.setRowCount(0);
            while(rs.next()){
                String blNo = String.valueOf(rs.getString("vis_block"));
                String hoNo = String.valueOf(rs.getString("vis_house_no"));
                String visName = String.valueOf(rs.getString("vis_name"));
                String vehicleNo = String.valueOf(rs.getString("vehicle_no"));
                String visCont = String.valueOf(rs.getString("vis_contact"));
                String visEntry = String.valueOf(rs.getString("vis_entry"));
                
                Timestamp tstamp = Timestamp.valueOf(visEntry);
                
                String dateStr = sdfDate.format(tstamp);
                String timeStr = sdfTime.format(tstamp);

                String tbData[] = {blNo,hoNo,visName,vehicleNo,visCont,dateStr,timeStr};

                tblModel.addRow(tbData);
            }
        } catch(Exception e){
            System.out.print(e);
        }
    }
    
    public void addLogsFilter() {
        try {
            Statement stmt = conn.createStatement();
            String query = "select * from visitor";
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel tblModel = (DefaultTableModel) logsTable.getModel();
            
            SimpleDateFormat sdfDate = new SimpleDateFormat("dd-MM-yyyy");
            sdfDate.setTimeZone(java.util.TimeZone.getTimeZone("IST"));

            SimpleDateFormat sdfTime = new SimpleDateFormat("hh:mm:ss a");
            sdfTime.setTimeZone(java.util.TimeZone.getTimeZone("IST"));

            tblModel.setRowCount(0);
            while(rs.next()){
                String blNo = String.valueOf(rs.getString("vis_block"));
                String hoNo = String.valueOf(rs.getString("vis_house_no"));
                String visName = String.valueOf(rs.getString("vis_name"));
                String vehicleNo = String.valueOf(rs.getString("vehicle_no"));
                String visCont = String.valueOf(rs.getString("vis_contact"));
                String visEntry = String.valueOf(rs.getString("vis_entry"));
                
                Timestamp tstamp = Timestamp.valueOf(visEntry);
                
                String dateStr = sdfDate.format(tstamp);
                String timeStr = sdfTime.format(tstamp);

                String tbData[] = {blNo,hoNo,visName,vehicleNo,visCont,dateStr,timeStr};

                tblModel.addRow(tbData);
            }
        } catch(Exception e){
            System.out.print(e);
        }
    }
    
    public void activeButton(JPanel panel, JPanel line) {
        panel.setBackground(new Color(86,70,120));
        line.setOpaque(true);
    }
    
    public void inactiveButton() {
        btnNewEntry.setBackground(new Color(64,43,100));
        btnLogs.setBackground(new Color(64,43,100));
        btnIndividualLogs.setBackground(new Color(64,43,100));
        btnLogOut.setBackground(new Color(64,43,100));
        
        jPanel10.setOpaque(false);
        jPanel11.setOpaque(false);
        jPanel12.setOpaque(false);
        jPanel13.setOpaque(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecurityDashboard().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnDownloadPdf;
    private javax.swing.JPanel btnIndDownloadPdf;
    private javax.swing.JPanel btnIndLogsSearch;
    private javax.swing.JPanel btnIndividualLogs;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnLogs;
    private javax.swing.JPanel btnLogsSearch;
    private javax.swing.JPanel btnNewEntry;
    private javax.swing.JPanel btnNext;
    private javax.swing.JPanel btnSendMail;
    private javax.swing.JComboBox<String> cbBlockNo;
    private javax.swing.JComboBox<String> cbIndBlockNo;
    private javax.swing.JComboBox<String> fromTimeCB;
    private javax.swing.JTable indLogsTable;
    private javax.swing.JPanel individualLogsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResiAddress;
    private javax.swing.JLabel lblResiContact;
    private javax.swing.JLabel lblResiName;
    private com.toedter.calendar.JDateChooser logsDateChooser;
    private javax.swing.JPanel logsPanel;
    private javax.swing.JTable logsTable;
    private javax.swing.JPanel navPane;
    private javax.swing.JPanel newEntryPanel;
    private javax.swing.JComboBox<String> toTimeCB;
    private javax.swing.JTextField txtHouseNo;
    private javax.swing.JTextField txtIndHouseNo;
    private javax.swing.JLabel txtSecurity;
    private javax.swing.JTextField txtVisitorContact;
    private javax.swing.JTextField txtVisitorName;
    private javax.swing.JTextField txtVisitorVehNo;
    private javax.swing.JPanel visitorEntryPanel;
    // End of variables declaration//GEN-END:variables
}
